source: /src/content
paths:
  uploads: uploads
collections_config:
  landing:
    path: landing
    output: false
    name: landing
    icon: notes
    _editables: {}
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config:
  landing:
    path: /src/content/landing
    parser: front-matter
editor: {}
timezone: Etc/UTC
